services:
  web:
    container_name: notes-php
    build: ./php
    ports:
      - "8080:80"
    networks:
      - app-network
    environment:
      DB_HOST: mysql_db
      DB_NAME: users_db
      DB_USER: root
      DB_PASSWORD: mypassword

  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - ./db:/docker-entrypoint-initdb.d

networks:
  app-network:
    driver: bridge